he realizado ajustes en el tamaño y vista del head y tipografía
Ngel07/esencias-bach pull request #2
Opened 2023-06-22 19:34 UTC by Ngel07

Se realiza cambio en el box del header
Ajusta la visualización del display

2023-06-22 19:36 UTC, dniskav requested changes
revisa el comentario

2023-06-22 19:36 UTC, dniskav commented on index.html
> -                <a href="#Fan-de-las-Flores">Fan de las Flores</a>
Porque le borraste el **#** ?

2023-06-22 19:39 UTC, Ngel07 commented on index.html
> -                <a href="#Fan-de-las-Flores">Fan de las Flores</a>
Este cambio fue un error que se ha corregido en el pull request 'body'

2023-06-22 19:40 UTC, merged

2023-06-26 06:43 UTC, dniskav commented on index.css
>      color:chocolate;
recuerda cambiar los colores a hexadecimal